create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  life_stage text not null default 'adult',
  mood integer not null default 50,
  dietary_intents text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  calories numeric not null default 0,
  protein numeric not null default 0,
  nutrients jsonb not null default '{}'::jsonb,
  eaten_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
